config/routes.rb
Rails.application.routes.draw do

  resources :answers
  scope '(:locale)', constraints: { locale: /en|es/ } do
    
    devise_for :users,
     controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations'
    }
    devise_scope :user do

      get 'invitation/accept',
        to: 'users/invitations#accept',
        as: :accept_invitation_request

      get 'users/invitations',
        to: 'users/invitations#index',
        as: :index_invitations

      get 'invitation/resend',
        to: 'users/invitations#resend',
        as: :resend_invitation

      get 'invitation/remove',
        to: 'users/invitations#remove',
        as: :remove_invitation

      authenticated :user do
        root :to => 'welcome#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'users/sessions#new', as: :unauthenticated_root
      end
      get '/profile/(:id)', :action => 'profile', :controller => 'users/registrations', as: 'profile'
      # DEV - Experimentacion con routes, sin exito
      ########OJO CON ESTA RUTA#####
      get 'users/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'
      # namespace :users do
      # end
      # resources :users, controller: 'users/invitations'
      # get 'users/invitations/(:id)/new', :action => 'new', :controller => 'users/invitations', as: 'invitations/new'
        # accept_user_invitation GET    /users/invitation/accept(.:format)           users/invitations#edit
        # accept_invitations GEST    /invitations/accept(.:format)     invitations#accept

      ########OJO CON ESTA RUTA#####

      #get '/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'

      put 'users/(:id)', to: 'users/registrations#update'
      post 'checking/email/', to: 'users/registrations#checkEmail'
    end


    resources :organizations
    get 'organizations_datatable_index', to: 'organizations#datatable_index'
    resources :status_entities
    get 'status_entities_datatable_index', to: 'status_entities#datatable_index'
    resources :type_entities
    get 'type_entities_datatable_index', to: 'type_entities#datatable_index'
    resources :roles
    get 'roles_datatable_index', to: 'roles#datatable_index'
    resources :users
    get 'users_datatable_index', to: 'users#datatable_index'

    resources :users_organizations do
      get 'data_json'
      get 'org_tree'
    end

    resources :scorecards do
      get 'questionType'
    end
    put  'scorecards/:id/:id2'                =>    'scorecards#onlyQuestionsAnswers'
    put  'scorecards/question/:id/:id2'       =>    'scorecards#removeQuestionsAnswers'
    resources :questions do

    end
    resources :requests_categories do
      resources :scorecards do
        resources :questions do
        end
        get 'onlyQuestionsAnswers'
      end
      get 'scorecard_association'
      #get 'index'
    end
    get 'requests_categories_datatable_index', to: 'requests_categories#datatable_index'
    resources :users_organizations_roles

    get 'users_organizations_datatable_index', to: 'users_organizations#datatable_index'

    resources :countries
    get 'countries_datatable_index', to: 'countries#datatable_index'
    resources :states do
      get 'get_counties_by_state'
    end
    get 'states_datatable_index', to: 'states#datatable_index'
    resources :counties
    get 'counties_datatable_index', to: 'counties#datatable_index'
    resources :cities
    get 'cities_datatable_index', to: 'cities#datatable_index'

    resources :currencies do

    end
    get 'currencies_datatable_index'                =>    'currencies#datatable_index'


  end
end

app/models/users_organization.rb
class UsersOrganization < ApplicationRecord
  acts_as_paranoid
  attr_accessor :managed_by

  belongs_to :status_entity
  belongs_to :user
  belongs_to :organization

  has_one  :users_organizations_role
  has_many :invitations, foreign_key: 'sent_by_id'
  accepts_nested_attributes_for :invitations, reject_if: lambda { |a| a[:email].blank? }, :allow_destroy => true
  
  accepts_nested_attributes_for :organization
  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :users_organizations_role

  validates :uuid, length: { in: 6..120 } #:created_by_uuid

  #before
  before_validation :load_uuid
  before_validation :set_status, on: :create
  scope :by_user, ->(user) { where(user_id: user.id).first } 
  scope :by_organiz, ->(organization) {
    select("users.full_name, users_organizations.id").
    joins(:user).
    where(organization_id: organization )
  }
  def self.managed_by users_organization_id
    select("users.full_name, users_organizations.id").
    joins(:user).
    where(users_organization_id: users_organization_id )    
  end
  def self.current
    Thread.current[:user_organization]
  end
  def self.current=(user_organization)
    Thread.current[:user_organization] = user_organization
  end

  private
    def  load_uuid
      self.uuid = SecureRandom.uuid
    end
    def set_status
      @status  = StatusEntity.by_class('UsersOrganization', 'Active')
      self.status_entity_id = @status[0].id
    end
end

app/controllers/users_organizations_controller.rb
class UsersOrganizationsController < ApplicationController
  
  before_action :load_available, only: [:index, :edit]    
  before_action :set_users_organization, only: [:show, :edit, :update, :destroy]

  def datatable_index
    render json: UsersOrganizationDatatable.new(view_context)
  end
  # GET /users_organizations/index
  def index
    @users_organization = UsersOrganization.new
    @users_organization.build_user
    @users_organization.build_organization
    @users_organizations_role = @users_organization.build_users_organizations_role
  end
  # GET /users_organizations/1/edit
  def edit
    add_breadcrumb params[:locale] == 'en' ? "edit" : "editar"
    @users_organizations_role = @users_organization.users_organizations_role
    users_org = UsersOrganization.managed_by(@users_organization.id)
    @data = users_org.collect { |key| { 'value': key[:id], 'text': key[:full_name] }}
    @data_json = @data.to_json 
    render 'index'
  end
  def create_member user, organization
    
  end
  # PATCH/PUT /users_organizations/1
  def update
    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          if @users_organization.update(users_organization_params)
            array = users_organization_params[:managed_by].tr('[]', '').split(',').map(&:to_i)
            unless array.blank?                
              array.each do |user|
                #unless user.to_i === 0              
                users_organization =  UsersOrganization.find_by(user)          
                users_organization.update_attributes!( users_organization_id: @users_organization.id )
                #end
              end
            end
          end
        end
      rescue => e
        format.js {  flash.now[:notice] = "ERROR"  }
      else
        format.js {  flash.now[:notice] = "Here is my flash notice"  }
      end
    end
  end
  def data_json
    @users_org = UsersOrganization.by_organiz(UsersOrganization.current.organization_id)
    if @users_org
      @data = @users_org.collect {|key| { 'value': key[:id], 'text': key[:full_name] }}
      render :json => @data.to_json 
    end  
  end
  def org_tree
    data = UsersOrganization
           .select("users_organizations.id, users.full_name as name, users_organizations.users_organization_id")
           .joins(:user)
           .where(organization_id: UsersOrganization.current.organization_id)
    hash = ActiveSupport::JSON.encode(data)
    json =  JSON.parse(hash)
    nested_hash = Hash[json.map{|e| [e['id'], e.merge(children: [])]}]
    nested_hash.each do |id, item|
      parent = nested_hash[item['users_organization_id']]
      parent[:children] << item if parent
    end
    tree = nested_hash.select { |id, item| item['users_organization_id'].nil? }.values
    fin = ActiveSupport::JSON.encode(tree)
    ar = fin.chop
    art = ar[1..ar.length]
    render :json => art    
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_organization
      @users_organization = UsersOrganization.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def users_organization_params
      params.require(:users_organization).permit(:id, :job_title, :managed_by, :users_organization_id, :status_entity_id,  users_organizations_role_attributes: [:id, :role_id])
    end
    def load_available
      @availableActive    = StatusEntity.where(class_name:'UsersOrganization', name: 'Active', status: true)
      @availableInactive  = StatusEntity.where(class_name:'UsersOrganization', name: 'Inactive', status: true)
    end
end

app/helpers/users_organizations_helper.rb
module UsersOrganizationsHelper
end

app/views/users_organizations/_form.html.erb
<%= form_for(@users_organization,  remote: true, :html => {class: "fv-form fv-form-bootstrap", id: "form_users_organization" }) do |f| %>
  
  <ul id="default-tabs-alt-1" class="nav nav-tabs tabs-alt-1">
    <li class="active"><a href="#default-tabs-new-alt-1" data-toggle="tab"><%=  params[:action] == "index" ? 'General information' : [@users_organization.user.first_name, @users_organization.user.last_name].join(' ')%></a></li>
    <li id="situation_organizational" style="/*display:none*/"><a href="#default-tabs-organization-alt-1" data-toggle="tab"><%= t 'views_user.org_position' %></a></li>
  </ul>
  <div class="tab-content">
    <div id="default-tabs-new-alt-1" class="tab-pane active">
      <%= f.fields_for :user do |ff| %>
        <div class="form-group">
          <%= ff.label :full_name, User.human_attribute_name(:full_name)+" (*)".html_safe, class:"control-label"%>
          <%= ff.text_field :full_name, class: "form-control", required: true, disabled: true%>
        </div>
        <div class="form-group">
          <%= ff.label :email, User.human_attribute_name(:email)+" (*)".html_safe, class:"control-label"%>
          <%= ff.text_field :email, class: "form-control", required: true, disabled: true%>
        </div>
      <% end %>
      <%= f.fields_for :organization do |fff| %>
        <div class="form-group">
          <%= fff.label :name, Organization.human_attribute_name(:name)+" (*)".html_safe, class:"control-label"%>
          <%= fff.text_field :name, class: "form-control", required: true, disabled: true%>
        </div>
      <% end %> 
      <%= f.fields_for :users_organizations_role do |q| %>
        <div class="form-group">
          <%= q.label :role_id, Organization.human_attribute_name(:role)+" (*)".html_safe, class:"control-label"%>
          <%= q.select( :role_id, options_for_select( Role.all.collect {|p| [p.name, p.id] }, @users_organizations_role.role_id ), {prompt:''}, { class: 'form-control chosen-select' , disabled: true })%>  
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :status_entity_id, Organization.human_attribute_name(:status_entity_id)+" (*)".html_safe, class:"control-label"%><p>
        <%= f.check_box(:status_entity_id, @users_organization.id.nil? ? {class: 'js-switch', disabled: true, checked: true } : {class: 'js-switch'}, @availableActive[0].id, @availableInactive[0].id) %> 
      </div>
    </div>
    <div id="default-tabs-organization-alt-1" class="tab-pane">
      <div class="form-group">
        <%= f.label  :users_organization_id, User.human_attribute_name(:users_organization_id), class: "control-label"%>
        <%= f.select(:users_organization_id, options_for_select( UsersOrganization.by_organiz(UsersOrganization.current.organization_id).collect {|p| [p.full_name, p.id] }, @users_organization.users_organization_id), {include_blank: ''}, { class: 'form-control' })%>
      </div>
      <div class="form-group">
        <%= f.label "managed_by", User.human_attribute_name(:users_organization_id), class: "control-label"%><p>
        <%= f.text_field "managed_by", class: "form-control input-tags-2", disabled: true, :data => {role: '' }, value:"#{@data_json}" %>
          <input type="hidden" class="tags" value="<%= @data_json %>" >         
      </div>
      <div class="form-group">
        <%= f.label :job_title, User.human_attribute_name(:job_title)+" (*)".html_safe, class: "control-label"%><p>
        <%= f.text_field :job_title, class: "form-control", required: true, disabled: true %>
      </div>
      <%= link_to "Org Tree", "", data: { toggle: "modal", target: "#default-modal" } %>
    </div>
  </div>
    <p>
    <input type="hidden" id="action" value="<%= params[:action] %>">
    <!-- Workaround to avoid corrupted XHR2 request body in IE10 / IE11 -->
    <input type="hidden" name="_dontcare">
    <div id="buttons" class="form-group" style="display: none">
        <% unless @users_organization.id.nil? %>
            <%= f.hidden_field :id %>
        <%= button_tag(type: 'button', id: "updateConfirm", class: "btn btn-primary" ) do %>
              <%= content_tag(:strong, 'Update') %>                     
          <%end%>   
      <% end %>
        <%= button_tag(type: 'button', id: "cancelConfirm", class: "btn btn-danger" ) do %>
              <%= content_tag(:strong, 'Cancel') %>                     
          <%end%>
    </div>
<% end %>

app/views/users_organizations/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <span aria-hidden="true" class="icon icon-documents"></span>
      <span class="main-text">
        <%= t('views_user_organization.title')%>
      </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-sm-8">
    <div class="block block-size-large">
      <div class="block-content-outer">
        <div class="block-content-inner">
          <div class="table-responsive">
            <table id="users_organizations-data" class="table table-striped table-hover" data-source="<%= users_organizations_datatable_index_path(format: "json") %>" >
              <thead title="Haga clic para ordenar por esta columna.">
                <tr>
                  <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%= User.human_attribute_name(:full_name)%></h5></th>
                  <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%= User.human_attribute_name(:email)%></h5></th>
                  <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%= User.human_attribute_name(:role)%></h5></th>
                  <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%= User.human_attribute_name(:status_entity_id)%></h5></th>
                  <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%= User.human_attribute_name(:actions)%></h5></th>
                </tr>
              </thead>
              <tbody align="center">
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-sm-4">
    <div class="block block-size-large">
      <div class="block-content-outer">
        <div class="block-content-inner" style="padding: 0px 5px 0px 5px;">
          <%= render partial: "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

<input id="modal_update" type="hidden" value="<%= I18n.t('views_user_organization.modals.update') %>"></input>
<input id="modal_delete" type="hidden" value="<%= I18n.t('views_user_organization.modals.delete') %>"></input>
<input id="modal_cancel" type="hidden" value="<%= I18n.t('views_user_organization.modals.cancel') %>"></input>
<%= render 'layouts/modal/org_tree_modal' %>

<script type="text/javascript">
  $('#modal-holder').append('<%= render "layouts/confirmation_modal" %>');
  $('#default-modal').appendTo("body"); 
$('[data-target="default-modal"]').on('click', function(e) {
      e.preventDefault();
      $('#default-modal').modal('show');
      /*var message = $('#modal_save').val();
      $('.modal-body').empty();
      $('.modal-body').append(message);*/
});

</script>
<%= javascript_include_tag "users_organizations"%>

app/views/users_organizations/update.js.erb
$("#flash").html('<%= j render partial: "shared/messages" %>');
Turbolinks.visit("<%= users_organizations_path %>");