config/routes.rb
Rails.application.routes.draw do

  resources :answers
  scope '(:locale)', constraints: { locale: /en|es/ } do
    
    devise_for :users,
     controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations'
    }
    devise_scope :user do

      get 'invitation/accept',
        to: 'users/invitations#accept',
        as: :accept_invitation_request

      get 'users/invitations',
        to: 'users/invitations#index',
        as: :index_invitations

      get 'invitation/resend',
        to: 'users/invitations#resend',
        as: :resend_invitation

      get 'invitation/remove',
        to: 'users/invitations#remove',
        as: :remove_invitation

      authenticated :user do
        root :to => 'welcome#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'users/sessions#new', as: :unauthenticated_root
      end
      get '/profile/(:id)', :action => 'profile', :controller => 'users/registrations', as: 'profile'
      # DEV - Experimentacion con routes, sin exito
      ########OJO CON ESTA RUTA#####
      get 'users/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'
      # namespace :users do
      # end
      # resources :users, controller: 'users/invitations'
      # get 'users/invitations/(:id)/new', :action => 'new', :controller => 'users/invitations', as: 'invitations/new'
        # accept_user_invitation GET    /users/invitation/accept(.:format)           users/invitations#edit
        # accept_invitations GEST    /invitations/accept(.:format)     invitations#accept

      ########OJO CON ESTA RUTA#####

      #get '/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'

      put 'users/(:id)', to: 'users/registrations#update'
      post 'checking/email/', to: 'users/registrations#checkEmail'
    end


    resources :organizations
    get 'organizations_datatable_index', to: 'organizations#datatable_index'
    resources :status_entities
    get 'status_entities_datatable_index', to: 'status_entities#datatable_index'
    resources :type_entities
    get 'type_entities_datatable_index', to: 'type_entities#datatable_index'
    resources :roles
    get 'roles_datatable_index', to: 'roles#datatable_index'
    resources :users
    get 'users_datatable_index', to: 'users#datatable_index'

    resources :users_organizations do
      get 'data_json'
      get 'org_tree'
    end

    resources :scorecards do
      get 'questionType'
    end
    put  'scorecards/:id/:id2'                =>    'scorecards#onlyQuestionsAnswers'
    put  'scorecards/question/:id/:id2'       =>    'scorecards#removeQuestionsAnswers'
    resources :questions do

    end
    resources :requests_categories do
      resources :scorecards do
        resources :questions do
        end
        get 'onlyQuestionsAnswers'
      end
      get 'scorecard_association'
      #get 'index'
    end
    get 'requests_categories_datatable_index', to: 'requests_categories#datatable_index'
    resources :users_organizations_roles

    get 'users_organizations_datatable_index', to: 'users_organizations#datatable_index'

    resources :countries
    get 'countries_datatable_index', to: 'countries#datatable_index'
    resources :states do
      get 'get_counties_by_state'
    end
    get 'states_datatable_index', to: 'states#datatable_index'
    resources :counties
    get 'counties_datatable_index', to: 'counties#datatable_index'
    resources :cities
    get 'cities_datatable_index', to: 'cities#datatable_index'

    resources :currencies do

    end
    get 'currencies_datatable_index'                =>    'currencies#datatable_index'


  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  acts_as_paranoid

  #Relationship
  belongs_to :status_entity #, :dependent => :destroy
  has_and_belongs_to_many :country

  #before
  before_destroy { country.clear }
  before_validation :load_uuid

  #scope :by_company, -> (company) { where(company_id: company.id) }
  scope :by_company, -> (company) {
    joins(country: :organizations).
    where("organizations.company_id = ?", company)
    group("currencies.id")
  } 

  private
  def  load_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

  respond_to :html, :json, :js
  before_action :breadcrumb
  before_action :set_avalable, only: [:index, :edit]
  before_action :set_currency, only: [:edit, :update, :destroy]

  def datatable_index
    render json: CurrencyDatatable.new(view_context)
  end
  def index
    @currency = Currency.new
  end
  def create
    @currency = Currency.new(currency_params)
    respond_to do |format|
      if @currency.save
        format.html { redirect_to currencies_url, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        #format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end
  def edit
    add_breadcrumb params[:locale] == 'en' ? "edit" : "editar"
    render 'index'
  end
  def update
    if @currency.update(currency_params)
      @success = true
      flash.now[:notice] = "Currency was successfully updated." 
    else
      flash.now[:error] = "Currency updated." 
    end
  end
  def destroy
    if @currency.destroy
      @success = true
      flash.now[:notice] = "Currency was successfully destroy." 
    else
      flash.now[:error] = "Currency error destroy." 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    def currency_params
      params.require(:currency).permit(:id, :name, :sort_name, :symbol, :status_entity_id, country_ids:[])
    end
    def breadcrumb
      add_breadcrumb I18n.t('views_currency.breadcrumb'), :currencies_path
    end
    def set_avalable
      @avalableActive    = StatusEntity.where(class_name:'Currency', name: 'Active', status: true)
      @avalableInactive  = StatusEntity.where(class_name:'Currency', name: 'Inactive', status: true)
    end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency, remote: true, :html => {class: "fv-form fv-form-bootstrap", id: "formCurrency" }) do |f| %>
    <div class="form-group">
        <%= f.label :name, Currency.human_attribute_name(:name)+" (*)".html_safe, class:"control-label"%>
        <%= f.text_field :name, class: "form-control", required: true, disabled: true%>
    </div>
    <div class="form-group">
        <%= f.label :sort_name, Currency.human_attribute_name(:sort_name)+" (*)".html_safe, class:"control-label"%>
        <%= f.text_field :sort_name, class: "form-control", required: true, disabled: true%>
    </div>
    <div class="form-group">
        <%= f.label :symbol, Currency.human_attribute_name(:symbol)+" (*)".html_safe, class:"control-label"%>
        <%= f.text_field :symbol, class: "form-control", required: true, disabled: true%>
    </div>
    <div class="form-group">
        <%= f.label :country_ids, Currency.human_attribute_name(:country_id)+" (*)".html_safe, class:"control-label"%><br />
        <%= f.select :country_ids, Country.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, class: 'form-control chosen-select', disabled: true %>
    </div>
    <div class="form-group">
        <%= f.label :status_entity_id, Currency.human_attribute_name(:status_entity_id)+" (*)".html_safe, class:"control-label"%><p>
        <%= f.check_box(:status_entity_id, @currency.id.nil? ? {class: 'js-switch', disabled: true, checked: true } : {class: 'js-switch', disabled: true }, @avalableActive[0].id, @avalableInactive[0].id) %> 
    </div>
    </p>
    <% if params[:action] == "index" %>
        <div class="form-group" id="button_new">
            <%= button_tag(type: 'button', id: "new", class: "btn btn-primary" ) do %>
                <%= content_tag(:strong, "New") %>                     
            <%end%>     
        </div>
    <% end %>
    <input type="hidden" id="action" value="<%= params[:action] %>">
    <!-- Workaround to avoid corrupted XHR2 request body in IE10 / IE11 -->
    <input type="hidden" name="_dontcare">
    <div id="buttons" class="form-group" style="display: none">
        <% unless @currency.id.nil? %>
            <%= f.hidden_field :id %>
            <%= button_tag(type: 'button', id: "updateConfirm", class: "btn btn-primary" ) do %>
                <%= content_tag(:strong, "Update") %>                
            <%end%>   
        <% else %>
            <%= button_tag(type: 'button', id: "saveConfirm", class: "btn btn-primary" ) do %>
                <%= content_tag(:strong, "Save") %>                     
            <%end%>
        <% end %>
            <%= button_tag(type: 'button', id: "cancelConfirm", class: "btn btn-danger" ) do %>
                <%= content_tag(:strong, "Cancel") %>                     
            <%end%>
    </div>
<% end %>

app/views/currencies/destroy.js.erb
<% if @success == true  %>
    $('#currencies').DataTable().ajax.reload();
    //Turbolinks.visit("<%= users_organizations_path %>");
<% end %>
  $("#small-modal").modal("hide")
  $("#flash").html('<%= j render partial: "shared/messages" %>');

app/views/currencies/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <span aria-hidden="true" class="icon icon-documents"></span>
      <span class="main-text">
        Currencies<%#= t 'views_currency.title' %>
      </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-sm-8">
    <div class="block block-size-large">
      <div class="block-content-outer">
          <div class="block-content-inner">
          <div class="table-responsive">          
            <table id="currencies" class="table table-striped table-hover" data-source="<%= currencies_datatable_index_path(format: "json") %>" >
                <thead title="Haga clic para ordenar por esta columna.">
                    <tr>
                      <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%=Currency.human_attribute_name(:name)%></h5></th> 
                      <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%=Currency.human_attribute_name(:sort_name)%></h5></th>   
                      <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%=Currency.human_attribute_name(:symbol)%></h5></th>
                      <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%=Currency.human_attribute_name(:symbol)%></h5></th>
                      <th><h5 style="font-weight: bold; margin-top: 5px; margin-bottom: 5px;" align="center"><%=Currency.human_attribute_name(:actions)%></h5></th>
                    </tr>
                </thead>
                <tbody align="center">
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-sm-4">
    <div class="block block-size-large">
      <div class="block-content-outer">
          <div class="block-content-inner" style="padding: 0px 5px 0px 5px;">
          <%= render partial: "form" %>
        </div>
      </div>
    </div>
  </div>
</div>
<input id="modal_save"   type="hidden" value="<%= I18n.t('views_currency.modals.save') %>"></input>
<input id="modal_update" type="hidden" value="<%= I18n.t('views_currency.modals.update') %>"></input>
<input id="modal_delete" type="hidden" value="<%= I18n.t('views_currency.modals.delete') %>"></input>
<input id="modal_cancel" type="hidden" value="<%= I18n.t('views_currency.modals.cancel') %>"></input>
<input id="modal_change" type="hidden" value="<%= I18n.t('views_currency.modals.change') %>"></input>
<%= render 'layouts/modal/confirmation_modal' %>
<%= javascript_include_tag "currencies"%>

app/views/currencies/update.js.erb
<% if @success == true  %>
    $('#currencies').DataTable().ajax.reload();
    //Turbolinks.visit("<%= users_organizations_path %>");
<% end %>
  $("#small-modal").modal("hide")
  $("#flash").html('<%= j render partial: "shared/messages" %>');