config/routes.rb
Rails.application.routes.draw do

  resources :answers
  scope '(:locale)', constraints: { locale: /en|es/ } do
    
    devise_for :users,
     controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations'
    }
    devise_scope :user do

      get 'invitation/accept',
        to: 'users/invitations#accept',
        as: :accept_invitation_request

      get 'users/invitations',
        to: 'users/invitations#index',
        as: :index_invitations

      get 'invitation/resend',
        to: 'users/invitations#resend',
        as: :resend_invitation

      get 'invitation/remove',
        to: 'users/invitations#remove',
        as: :remove_invitation

      authenticated :user do
        root :to => 'welcome#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'users/sessions#new', as: :unauthenticated_root
      end
      get '/profile/(:id)', :action => 'profile', :controller => 'users/registrations', as: 'profile'
      # DEV - Experimentacion con routes, sin exito
      ########OJO CON ESTA RUTA#####
      get 'users/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'
      # namespace :users do
      # end
      # resources :users, controller: 'users/invitations'
      # get 'users/invitations/(:id)/new', :action => 'new', :controller => 'users/invitations', as: 'invitations/new'
        # accept_user_invitation GET    /users/invitation/accept(.:format)           users/invitations#edit
        # accept_invitations GEST    /invitations/accept(.:format)     invitations#accept

      ########OJO CON ESTA RUTA#####

      #get '/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'

      put 'users/(:id)', to: 'users/registrations#update'
      post 'checking/email/', to: 'users/registrations#checkEmail'
    end


    resources :organizations
    get 'organizations_datatable_index', to: 'organizations#datatable_index'
    resources :status_entities
    get 'status_entities_datatable_index', to: 'status_entities#datatable_index'
    resources :type_entities
    get 'type_entities_datatable_index', to: 'type_entities#datatable_index'
    resources :roles
    get 'roles_datatable_index', to: 'roles#datatable_index'
    resources :users
    get 'users_datatable_index', to: 'users#datatable_index'

    resources :users_organizations do
      get 'data_json'
      get 'org_tree'
    end

    resources :scorecards do
      get 'questionType'
    end
    put  'scorecards/:id/:id2'                =>    'scorecards#onlyQuestionsAnswers'
    put  'scorecards/question/:id/:id2'       =>    'scorecards#removeQuestionsAnswers'
    resources :questions do

    end
    resources :requests_categories do
      resources :scorecards do
        resources :questions do
        end
        get 'onlyQuestionsAnswers'
      end
      get 'scorecard_association'
      #get 'index'
    end
    get 'requests_categories_datatable_index', to: 'requests_categories#datatable_index'
    resources :users_organizations_roles

    get 'users_organizations_datatable_index', to: 'users_organizations#datatable_index'

    resources :countries
    get 'countries_datatable_index', to: 'countries#datatable_index'
    resources :states do
      get 'get_counties_by_state'
    end
    get 'states_datatable_index', to: 'states#datatable_index'
    resources :counties
    get 'counties_datatable_index', to: 'counties#datatable_index'
    resources :cities
    get 'cities_datatable_index', to: 'cities#datatable_index'

    resources :currencies do

    end
    get 'currencies_datatable_index'                =>    'currencies#datatable_index'


  end
end

app/views/shared/_body.html.erb
<!-- START Body Container -->
<div id="body-container">
 <% if user_signed_in? %>
  <%= render partial: "shared/sidebar" %>
  <!-- START Right Column -->
  <div id="right-column">
 <% end %>
    <div class="right-column-content">
      <% if user_signed_in? %>
       <%= render partial: "shared/breadcrumb" %>
      <% end %>
      <!--<div class="row">-->
        <%= yield %>
      <!--</div>-->
    </div>
  </div>
  <style media="screen">

    table.dataTable thead .sorting, 
    table.dataTable thead .sorting_asc, 
    table.dataTable thead .sorting_desc {
        background : none;
    }
    .dataTables_wrapper .dataTables_paginate .paginate_button {
      padding: 0px  !important;
      margin-left: 0px  !important;
      border: 0px !important;
    }
    .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
      border: 0px !important;
    }
    table.dataTable.no-footer {
      border-bottom: 0px !important;
    }
  </style>

</div>

app/views/shared/_breadcrumb.html.erb
<div class="row">
  <div class="col-xs-12">
    <ol class="breadcrumb">
      <li>
        <%= render_breadcrumbs %>
      </li>
    </ol>
  </div>
</div>

app/views/shared/_footer.html.erb
  <!-- START Footer Container -->
    <div id="footer-container">
      <div class="footer-content">
      &copy; <%= link_to('ixanaui',authenticated_root_path)%> <%= Time.now.year %>
      </div>
    </div>
    <!-- END Footer Container -->
  </div>
  <!-- END Right Column -->
</div>
    <!-- END Body Container -->

app/views/shared/_messages.html.erb
<div data-alert class="alert-box">
	<script type="text/javascript">
	    <% flash.each do |f| %>
	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
	       toastr['<%= type %>']('<%= f[1] %>', '<%= type %>');
	    <% end %>
   </script>
</div>

app/views/shared/_sidebar.html.erb
<!-- START Left Column -->
<div id="left-column" class=""> <!-- NOTE TO READER: Accepts the following class(es) "menu-icon-only", "fixed" class -->
  <div id="mainnav">
    <ul class="mainnav"> <!-- NOTE TO READER: Accepts the following class(es) "animate" class -->
      <li class="menu-item-top <%=  params[:controller] == "welcome" ? 'selected' : ''%>">
        <%= link_to authenticated_root_path, class: "top" do %>
        <span class="main-menu-icon">
          <span aria-hidden="true" class="icon icon-grid-big"></span>
        </span>
        <span class="main-menu-text"><%#= t 'sidebar.dashboard' %></span>
        <% end %>
      </li>
      <li class="menu-item-top">
        <a href="#" class="top">
          <span class="main-menu-icon">
            <span aria-hidden="true" class="icon icon-settings"></span>
          </span>
          <span class="main-menu-text"><%= t('sidebar.settings') %></span>
        </a>
        <ul>
          <li><%= link_to t('sidebar.settings.users'), users_path %></li>
          <li><%= link_to t('sidebar.settings.users_organizations'), users_organizations_path %></li>
          <li><%= link_to t('sidebar.settings.requests_category'), requests_categories_path %></li>
          <li><%= link_to t('sidebar.settings.organizations'), organizations_path %></li>
          <li><%= link_to t('sidebar.settings.roles'), roles_path %></li>
          <li><%= link_to t('sidebar.settings.currencies'), currencies_path %></li>
          <li><%= link_to t('sidebar.settings.countries'), countries_path %></li>
          <li><%= link_to t('sidebar.settings.states'), states_path %></li>
          <li><%= link_to t('sidebar.settings.counties'), counties_path %></li>
          <li><%= link_to t('sidebar.settings.cities'), cities_path %></li>
          <li><%= link_to t('sidebar.settings.type_entities'), type_entities_path %></li>
          <li><%= link_to t('sidebar.settings.status_entities'), status_entities_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
<!-- END Left Column -->

app/views/shared/_top.html.erb
<!-- START Header Container -->
<div id="header-container">
  <div class="header-bar navbar navbar-inverse" role="navigation"> <!-- NOTE TO READER: Accepts the following class(es) "navbar-fixed-top" class -->
    <div class="container">
      <div class="navbar-header">
        <!-- START logo -->
        <div class="logo">
          <%#= link_to(image_tag("required/PonderIn.png", class: "default-logo", width: "156", height: "44"), "/") %>
          <%= link_to authenticated_root_path, class: "top" do
          image_tag("required/PonderIn.png", class: "default-logo", width: "156", height: "44")
          end %>
        </div>
        <!-- END logo -->
        <!-- START Mobile Menu Toggle -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- END Mobile Menu Toggle -->
        <!-- START Language Selector -->
        <div class="header-language"> <!-- NOTE TO READER: Accepts the following class(es) "animate" class -->
          <ul>
            <li>
              <a href="#" class="language-closed">
                <span aria-hidden="true" class="icon icon-wireframe-globe"></span>
                <span class="main-text"><%= t 'top.language' %></span>
              </a>
              <a href="#" class="language-opened">
                <span aria-hidden="true" class="icon icon-cross"></span>
                <span class="main-text"><%= t 'top.language' %></span>
              </a>
              <ul>
                <li class="language-list-item">
                  <div class="language-block">
                    <%= link_to  url_for( :locale => 'en' ), class: 'lenguaje' do %>
                    <span class="language-flag">
                      <%= image_tag("optional/flags/united-states.png", options:{width: "32", height: "32", alt: "english-flag"}) %>
                    </span>
                    <span class="language-name">
                      <%= t 'top.english' %>
                    </span>
                    <% end %>
                  </div>
                </li>
                <li class="language-list-item">
                  <div class="language-block">
                    <%= link_to  url_for( :locale => 'es' ), class: 'lenguaje' do %>
                    <span class="language-flag">
                      <%= image_tag("optional/flags/mexico.png", options:{width: "32", height: "32", alt: "espanol-flag"}) %>
                    </span>
                    <span class="language-name">
                      <%= t 'top.spanish' %>
                    </span>
                    <%end -%>
                  </div>
                </li>
                <li class="language-list-item">
                  <div class="language-block">
                    <%= link_to  url_for( :locale => 'fr' ), class: 'lenguaje' do %>
                    <span class="language-flag">
                      <%= image_tag("optional/flags/canada.png", options:{width: "32", height: "32", alt: "-flag"}) %>
                    </span>
                    <span class="language-name">
                      Français
                    </span>
                    <%end -%>
                  </div>
                </li>
                <li class="language-list-item">
                  <div class="language-block">
                    <%= link_to  url_for( :locale => 'pr' ), class: 'lenguaje' do %>
                    <span class="language-flag">
                      <%= image_tag("optional/flags/brazil.png", options:{width: "32", height: "32", alt: "espanol-flag"}) %>
                    </span>
                    <span class="language-name">
                      Português
                    </span>
                    <%end -%>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>

        <!-- START Header Info Container -->
        <div class="header-info">
          <!-- START Header User Profile -->
          <div class="header-profile"> <!-- NOTE TO READER: Accepts the following class(es) "animate" class -->
            <ul class="header-profile-menu">
              <li>
                <a href="#" class="top">
                  <span class="header-profile-menu-icon">
                    <%= image_tag(current_user.avatar.url(:thumb), width: 39, height: 39) %>
                  </span>
                  <%= [current_user.first_name,current_user.last_name].join(' ') %>
                  <span class="main-menu-text">
                    <%#= current_user.full_name_cache%>
                    <i class="icon icon-arrow-down-bold-round icon-size-small"></i>
                  </span>
                </a>
                <ul>
                  <li>
                    <%= link_to profile_path(current_user) do  %>
                    <span aria-hidden="true" class="icon icon-user"></span>
                    <span class="main-text"><%= t 'top.profile' %></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to index_invitations_path do  %>
                    <span aria-hidden="true" class="icon icon-user"></span>
                    <span class="main-text"><%= t 'top.invitations' %></span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do  %>
                    <span aria-hidden="true" class="icon icon-arrow-curve-right"></span>
                    <span class="main-text"><%= t 'top.logout' %></span>
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <!-- END Header User Profile -->
        </div>
        <!-- END Header Info Container -->

      </div>
    </div>
  </div>
</div>
<!-- END Header Container -->