config/routes.rb
Rails.application.routes.draw do

  resources :answers
  scope '(:locale)', constraints: { locale: /en|es/ } do
    
    devise_for :users,
     controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      confirmations: 'users/confirmations',
      invitations: 'users/invitations'
    }
    devise_scope :user do

      get 'invitation/accept',
        to: 'users/invitations#accept',
        as: :accept_invitation_request

      get 'users/invitations',
        to: 'users/invitations#index',
        as: :index_invitations

      get 'invitation/resend',
        to: 'users/invitations#resend',
        as: :resend_invitation

      get 'invitation/remove',
        to: 'users/invitations#remove',
        as: :remove_invitation

      authenticated :user do
        root :to => 'welcome#index', as: :authenticated_root
      end
      unauthenticated :user do
        root :to => 'users/sessions#new', as: :unauthenticated_root
      end
      get '/profile/(:id)', :action => 'profile', :controller => 'users/registrations', as: 'profile'
      # DEV - Experimentacion con routes, sin exito
      ########OJO CON ESTA RUTA#####
      get 'users/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'
      # namespace :users do
      # end
      # resources :users, controller: 'users/invitations'
      # get 'users/invitations/(:id)/new', :action => 'new', :controller => 'users/invitations', as: 'invitations/new'
        # accept_user_invitation GET    /users/invitation/accept(.:format)           users/invitations#edit
        # accept_invitations GEST    /invitations/accept(.:format)     invitations#accept

      ########OJO CON ESTA RUTA#####

      #get '/invitations/(:id)', :action => 'index', :controller => 'users/invitations', as: 'invitations'

      put 'users/(:id)', to: 'users/registrations#update'
      post 'checking/email/', to: 'users/registrations#checkEmail'
    end


    resources :organizations
    get 'organizations_datatable_index', to: 'organizations#datatable_index'
    resources :status_entities
    get 'status_entities_datatable_index', to: 'status_entities#datatable_index'
    resources :type_entities
    get 'type_entities_datatable_index', to: 'type_entities#datatable_index'
    resources :roles
    get 'roles_datatable_index', to: 'roles#datatable_index'
    resources :users
    get 'users_datatable_index', to: 'users#datatable_index'

    resources :users_organizations do
      get 'data_json'
      get 'org_tree'
    end

    resources :scorecards do
      get 'questionType'
    end
    put  'scorecards/:id/:id2'                =>    'scorecards#onlyQuestionsAnswers'
    put  'scorecards/question/:id/:id2'       =>    'scorecards#removeQuestionsAnswers'
    resources :questions do

    end
    resources :requests_categories do
      resources :scorecards do
        resources :questions do
        end
        get 'onlyQuestionsAnswers'
      end
      get 'scorecard_association'
      #get 'index'
    end
    get 'requests_categories_datatable_index', to: 'requests_categories#datatable_index'
    resources :users_organizations_roles

    get 'users_organizations_datatable_index', to: 'users_organizations#datatable_index'

    resources :countries
    get 'countries_datatable_index', to: 'countries#datatable_index'
    resources :states do
      get 'get_counties_by_state'
    end
    get 'states_datatable_index', to: 'states#datatable_index'
    resources :counties
    get 'counties_datatable_index', to: 'counties#datatable_index'
    resources :cities
    get 'cities_datatable_index', to: 'cities#datatable_index'

    resources :currencies do

    end
    get 'currencies_datatable_index'                =>    'currencies#datatable_index'


  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    skip_before_action :set_current_user_organization, :only => [:new, :create, :edit, :show]

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    #  super(resource_name, resource)
    sign_in(resource)
    authenticated_root_path
    #any_path # redirect_to is not necessary
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  respond_to :html, :json, :js
  
  before_action :set_status, only: [:create, :accept, :remove]
  before_action :set_invitation, only: [:remove]
  before_action :set_invitations, only: [:index, :remove]
  skip_before_action :set_current_user_organization, :only => [:accept, :create, :edit, :update]

  def index
  end
  def new
    self.resource = resource_class.new
    respond_modal_with @invitation
  end
  def create
    hashes = Array.new
    begin
      ActiveRecord::Base.transaction do
        params[:user][:emails].each do |email|
          exists = Invitation.by_user_organiz(email, UsersOrganization.current.organization_id)
          #puts exists.empty?
          unless !exists.present?
            hashes.push({ email: email, valid: false })
          else  
            hashes.push({ email: email, valid: true })
            Invitation.create!(email: email, 
                          sent_by_id: UsersOrganization.current.id)   
          end        
        end
      end
    rescue => e
      render json: { success: false, 
                     message: I18n.t('views_user.save_error'), }
    else
      #redirect_to index_invitations_path, notice: 'Invitations was successfully created.'
      render json: hashes
    end
  end
  def accept
    invitation =  Invitation.by_token(params[:token])
    exists     =  User.find_by(email: invitation[0].email)  
    if ((invitation.present?) && (invitation[0].status_entity_id === @statusPending[0].id))
      ActiveRecord::Base.transaction do    
        unless User.exists?(email: invitation[0].email )
          user = User.invite!(
            invitation_par(invitation[0], @statusActv[0].id).merge(
              skip_invitation: true
            ),
            invitation[0].sent_by
          )
          create_users_organization user, invitation
          redirect_to accept_invitation_url(user, invitation_token: user.raw_invitation_token)      
        else
          create_users_organization exists, invitation
          redirect_to authenticated_root_path, notice: 'Users organization was successfully created.'
        end
      end
    else        
      flash[:error] = t('en.invitations.accept.not_valid')
      redirect_to authenticated_root_path
    end
  end
  def resend
    invitation = Invitation.find_by(invitation_token: params[:token])
    Mailer.instructions(invitation).deliver_later  
    render json: { success: true }
  end
  def update
    super
  end
  def remove
    unless @invitation.status_entity_id == @statusAccepted[0].id
      if @invitation.destroy
        @success = true
        flash.now[:notice] = "Here is my flash notice" 
      else
        flash.now[:error] = "Here is my flash notice" 
      end
    else
      flash.now[:error] = "NO notice"
    end
    #respond_to do |f|
    #  f.js  
    #end
  end

  private

  def breadcrumb
    #add_breadcrumb I18n.t('views_company.breadcrumb'), :admin_companies_path
  end
  def set_status
    @statusAccepted = StatusEntity.where(class_name:'Invitation', name: 'Accepted', status: true)
    @statusPending  = StatusEntity.where(class_name:'Invitation', name: 'Pending', status: true)
    @statusRejected = StatusEntity.where(class_name:'Invitation', name: 'Rejected', status: true)
    @statusActv     = StatusEntity.where(class_name:'User', name: 'Active', status: true)
  end
  def set_invitation
    @invitation = Invitation.find(params[:id])
  end
  def invitation_par invitation, status
    { email: invitation.email, status_entity_id: status }
  end
  def set_invitations
    @invitations = Invitation.get_by_users_organization(UsersOrganization.current.id)
                             .search(params[:search])
                             .paginate(:per_page => 8, :page => params[:page])    
  end
  def create_users_organization user, invitation
    users_organization  =  UsersOrganization.create!(user_id: user.id, 
                                             organization_id: invitation[0].organization_id,
                                      users_organization_id:  invitation[0].sent_by_id)
    users_org_role      =  users_organization.build_users_organizations_role # = users_organization
    users_org_role.role =  Role.where(name: 'Member').first
    users_org_role.save
    user.update(invitation_sent_at: Time.now.utc)
    invitation.update(status_entity_id: @statusAccepted[0].id)
  end

  protected
  def invite_resource(&block)
    @user = User.find_by(email: invite_params[:email])
    # @user is an instance or nil
    if @user && @user.email != current_user.email
      # invite! instance method returns a Mail::Message instance
      @user.invite!(current_user)
      # return the user instance to match expected return type
      @user
    else
      # invite! class method returns invitable var, which is a User instance
      resource_class.invite!(invite_params, current_inviter, &block)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_before_action :set_current_user_organization, :only => [:new, :create, :edit, :update]

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :set_status, only: [:new]
  skip_before_action :set_current_user_organization, :only => [:new, :create, :checkEmail, :profile ]


  #prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  #skip_before_action :authenticate_user!, only: [:new, :create, :cancel]
  #skip_before_filter :require_no_authentication, :only => [ :new, :create]
  # load_and_authorize_resource



  # GET /resource/sign_up
  def new
    resource  = build_resource({})
    users_org = resource.users_organizations.build
    organizat = users_org.build_organization
    users_org.invitations.build
    respond_with self.resource
  end

  def checkEmail
    @email = User.where(email: params[:user][:email])
    if @email.count == 0
        render json: {  valid: true }
    else
        render json: {  valid: false }
    end
  end

  def profile
    @user = User.find(params[:id])
    if @user.organization_id != nil
      @organization = Organization.find(@user.organization_id)
    end
    add_breadcrumb t('breadcrumbs.profile'), profile_path(current_user.id)
  end

  def update
    # required for settings form to submit when password is left blank
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(user_params)
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      # sign_in @user, :bypass => true
      bypass_sign_in(@user)
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end


  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    #super(resource)
    sign_out resource
    new_user_session_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

    def sign_up_params
      #allow = [:email, :your_fields, :password, :password_confirmation]
      params.require(resource_name).permit(:first_name, :second_last_name, :middle_name, :last_name, :organization_name, :email, :password, :password_confirmation, :status, :status_entity_id,                                   
                                           users_organizations_attributes: [ :id,
                                           organization_attributes: [:id, :name, :status_entity_id],
                                           invitations_attributes: [:id, :email, :status_entity_id]])
    end
    def set_status
      @statusUserAct   = StatusEntity.where(class_name:'User', name: 'Active', status: true)
      @statusUserInact = StatusEntity.where(class_name:'User', name: 'Inactive', status: true)
      @statusOrgAct    = StatusEntity.where(class_name:'Organization', name: 'Active', status: true)
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # prepend_before_action :require_no_authentication, only: [:new, :create, :cancel]
  # skip_before_action :authenticate_user!, only: [:new, :create, :cancel]
  skip_before_action :set_current_user_organization, :only => [:new, :create, :destroy ]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/invitations/_form.html.erb
<%= form_for(@invitation, remote: request.xhr?, html: {data: {modal: true }})  do |f| %>
<div class="form-group">
  <%= f.label :email, User.human_attribute_name(:email) + " (*)".html_safe, class:"control-label" %>
  <%= f.text_field :email, class: "form-control",  placeholder: true ,required: true %>
</div>

<%= f.submit t('registration.form.submit'),  class: "btn btn-success" %>

<% end %>

app/views/users/invitations/_invitations.html.erb
<div class="table-responsive">  
	<table class="table table-striped table-hover">
	  <tbody>
	   <% @invitations.each do |invitation| %>
	    <tr id="invitation_<%= invitation.id%>">
	      <td style="width: 45%">
	      	<div style="padding-left: 15px" class="row">
	      		<div align="center" class="col-md-1">   
	      		   <%= invitation.user_id.nil? ? fa_icon("envelope-o", style:"padding-left: 5px") : image_tag(User.find(invitation.user_id).avatar.url(:thumb), width: 23, height: 23, class: "list-thumbnail") %>
	      		</div>
	      		<div align="left" style="padding-left: 0px" class="col-md-10">
					<% if invitation.user_id.nil?%>
					   <%= invitation.email %>					  
					<% else %>
					  <%= invitation.full_name %>
					<% end %>
					<span class="loading" style="display: none"><%= image_tag("ajax-loader.gif") %></span>
					<span id="resend_invitation"><%= invitation.status == 'Pending' ? link_to("(Resend invitation)", resend_invitation_path(token: invitation.invitation_token), remote: true, class: "resend") : '' %></span>
	      		</div>
	      	</div> 	
	      </td>
	      <td style="width: 15%">
	      	 <span class="label label-warning"><%= invitation.status %></span>
	      </td>
	      <td onload="return ran_col()" align="right" style="width: 20%">
	      	    <div><%= "#{['Invited', invitation.created_at.strftime("%B %e, %Y")].join(' ')}" %></div><br>
	      		<div class="posts_to" style="margin-top: -17px"><a><%="#{['by'.html_safe, invitation.by_full_name].join(' ')}"%></a></div>
	      </td>
	      <td align="right" style="width: 20%; padding-right: 45px"><%=
	      link_to("<span style='cursor:pointer' class='icon-cross icon-size-medium highlight-color-gray-text deleteRow'></span>".html_safe, remove_invitation_path(id: invitation.id), remote: true) %></td>
	    </tr>
	    <% end %>
	  </tbody>
	</table>
</div>

<style type="text/css">
  table {
    border-collapse: collapse;
    width: 100%;
  }
  .fa { transform: scale(1.4,1.4); }
</style>
<script type="text/javascript">

	$(".resend")
      .bind("ajax:beforeSend", function(){
        $(this).closest('tr').find('.loading').toggle();
      }).bind("ajax:success", function(event, data, status, xhr) {
        $(this).closest('tr').find('.col-md-10').append('<span class="label label-success"><strong>Invitation resend</strong></span>');
      }).bind("ajax:complete", function(){
	    $(this).closest('tr').find('.loading').remove();
    	$(this).closest('tr').find('#resend_invitation').remove();
      });


    function ran_col() { //function name
        var color = '#'; // hexadecimal starting symbol
        var letters = ['000000','FF0000','00FF00','0000FF','FFFF00','00FFFF','FF00FF','C0C0C0']; //Set your colors here
        color += letters[Math.floor(Math.random() * letters.length)];
        $(".posts_to").css("background", "blue"); // Setting the random color on your div element.
    }
</script>

app/views/users/invitations/edit.html.erb
<div class="standalone-page">
  <div class="standalone-page-content" data-border-top="multi">
    <div class="standalone-page-block">
      <div class="row">
        <div class="col-xs-12">
          <h2 class="heading">
          </h2>
        </div>
      </div>
      <%#= form_for( @invitation, url: accept_invitations_path(@invitation), html: { method: :put, role: 'form'} ) do |f| %>
      <%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put, role: 'form'} do |f| %>
        <div class="row">
            <div class="col-md-12"> 
                <div class="form-group">
                  <%= f.label :first_name, "First name (*)".html_safe, class:"control-label" %>
                  <%= f.text_field :first_name, class: "form-control",  placeholder: "First name" ,required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :last_name, "Last name (*)".html_safe, class:"control-label" %>
                  <%= f.text_field :last_name, class: "form-control", placeholder: "Last name", required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :email, "Email (*)".html_safe, class:"control-label" %>
                  <%= f.text_field :email, class: "form-control", placeholder: "Email", required: true %>
                </div>  
                <div class="form-group">
                  <%= f.label :password, "Password (*)".html_safe, class:"control-label" %>
                  <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: true %>
                </div>
                <div class="form-group">
                  <%= f.label :password_confirmation, "Password confirmation (*)".html_safe, class:"control-label" %>
                  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password again", required: true %>
                </div>    
                <%= f.hidden_field :status_entity_id, class: "form-control", value:'1' %>
                <%= f.hidden_field :status, class: "form-control", value:'1' %>
                <%= f.hidden_field :invitation_token %>          

                <%= f.text_field :organization_id %>          
              <!-- Previous/Next buttons -->
              <ul class="pager wizard">
                  <li id="create"><%= f.submit t("devise.invitations.edit.submit_button"), class: "btn btn-success" %></li>
              </ul>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h2><%= t 'devise.invitations.edit.header' %></h2>
<style type="text/css">
/**
 * Pages Signin (Type 1), Signup
 */
/* Sign In, Forgot Password, Register Pages */
.standalone-page {
  margin: 100px auto 20px;
  max-width: 380px;
}
.standalone-page.registration-page {
  margin: 46px auto 20px;
}
.standalone-page .standalone-page-logo {
  text-align: center;
}
</style>
<%#= simple_form_for resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put } do |f| %>
  <%#= devise_error_messages! %>
  <%#= f.hidden_field :invitation_token %>

  <%#= f.input :password %>
  <%#= f.input :password_confirmation %>

  <%#= f.button :submit, t("devise.invitations.edit.submit_button") %>
<%# end %>

app/views/users/invitations/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      <span aria-hidden="true" class="icon icon-email-upload"></span>
      <span class="main-text">
        Invitations<%#= t 'views_user.profile_title' %>
      </span>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="block block-size-large">
      <div class="block-content-outer">
        <div class="block-content-inner">

          <div class="tab-content" style="padding: 20px 20px 20px 20px">
              <div class="mailbox-container mailbox-email-list">
                  <div class="mailbox-controls">
                  <!--<div class="checkbox email-select-all">
                    <label>
                      <input type="checkbox">
                      <span class="main-text hidden-xs hidden-sm">
                        Select All
                      </span>
                    </label>
                  </div>-->
                  <%#= link_to 'Create category', new_user_invitation_path, data: { modal: true } %>
                    <%= link_to new_user_invitation_path, class: "btn btn-primary email-mark-read", data: { modal: true } do %>
                      <!--<span class="glyphicon glyphicon-saved"></span>-->
                      <span class="hidden-xs hidden-sm">
                        <b>Send invitation</b>
                      </span>
                    <% end %>
                    <div class="email-pager-top">
                      <%= form_tag index_invitations_path, :method => 'get', :id => "invitations_search", remote: true, role:'form' do %>                    
                          <%#= submit_tag "Search", :name => nil %>
                          <div class="inner-addon left-addon">
                              <i class="glyphicon glyphicon-search"></i>
                              <%= text_field_tag :search, params[:search], class:"form-control", id:"mailbox-search-bar", placeholder:"Search invitations..."%>
                          </div>
                      <% end %>
                    </div>
                  </div>
                <div style="margin-top: 30px" id="invitations"><%= render 'invitations' %></div>
                <div class="row email-pager-bottom" style="margin-top: -20px">
                  <div style="padding-top:20px" align="left" class="col-md-6 page_info" >
                    <%= page_entries_info @invitations %>
                  </div>
                  <div id="page_links" class="col-md-6">
                    <%#= paginate @invitations %>
                    <%#= will_paginate @invitations, :renderer => 'RemoteLinkPaginationHelper::LinkRenderer', class: 'justify-content-center' %>
                    <%= will_paginate @invitations, renderer: 'RemoteLinkPaginationHelper::LinkRenderer' %>
                  </div>                  
                </div>
              </div>
          
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<%#= page_entries_info @posts %>
<style type="text/css">

.pagination {
  margin: 10px 0;
}
  /**
 * Pages Mailbox
 */
/* Mailbox - General */
.mailbox-search {
  clear: both;
  margin-top: 32px;
}
.mailbox-menu {
  margin-bottom: 20px;
}
.mailbox-menu .mailbox-compose-outer {
  border-bottom: 1px solid #dedede;
  margin-bottom: 20px;
  padding-bottom: 20px;
  overflow: hidden;
}
.mailbox-menu .mailbox-tags {
  border-top: 1px solid #dedede;
  padding-top: 10px;
}
.mailbox-menu .mailbox-tags .badge {
  margin-bottom: 5px;
}
.mailbox-container {
  /*padding: 20px 15px;
  border-top: 3px solid #4596f1;
  border-left: 1px solid #dedede;
  border-right: 1px solid #dedede;
  border-bottom: 1px solid #dedede !important;*/
}
.mailbox-email-list .mailbox-controls .email-select-all {
  float: left;
  margin: 5px 35px 5px 0;
}
.mailbox-email-list .mailbox-controls .email-select-all label {
  padding-left: 8px;
}
.mailbox-email-list .mailbox-controls .email-select-all label input {
  display: none;
}
.mailbox-email-list .mailbox-controls .email-select-all label .checkbox-actual {
  float: left;
}
.mailbox-email-list .mailbox-controls .email-select-all label .main-text {
  float: left;
  padding-left: 6px;
  padding-top: 2px;
}

.mailbox-email-list .email-pager-top {
  float: right;
  width: 300px;
}
.mailbox-email-list .email-pager-top .email-pager-count {
  float: right;
  margin-right: 10px;
  margin-top: 6px;
}
.mailbox-email-list .email-pager-top .email-pager-container {
  float: right;
}
.mailbox-email-list .email-pager-top,
.mailbox-email-list .email-pager-bottom {
  text-align: right;
}
.mailbox-email-list .email-pager-top .email-pager-count,
.mailbox-email-list .email-pager-bottom .email-pager-count {
  margin-bottom: 5px;
}

/* enable absolute positioning */
.inner-addon { 
    position: relative; 
}

/* style icon */
.inner-addon .glyphicon {
  position: absolute;
  padding: 10px;
  pointer-events: none;
}

/* align icon */
.left-addon .glyphicon  { left:  0px;}
.right-addon .glyphicon { right: 0px;}

/* add padding  */
.left-addon input  { padding-left:  30px; }
.right-addon input { padding-right: 30px; }

</style>

app/views/users/invitations/index.js.erb
$('#invitations').html('<%= escape_javascript(render("invitations")) %>');
$('#page_links').html('<%= escape_javascript(paginate(@invitations, :remote => true).to_s) %>');
$('.page_info').html('<%= escape_javascript(page_entries_info(@invitations, :remote => true).to_s) %>');

app/views/users/invitations/new.html.erb
<%= render 'layouts/modal/new_invitations_modal' %>

app/views/users/invitations/remove.js.erb
<% if @success == true  %>
//	$('#invitation_<%= @invitation.id %>').remove();
	$('#invitations').html('<%= escape_javascript(render("invitations")) %>');
	$('#page_links').html('<%= escape_javascript(paginate(@invitations, :remote => true).to_s) %>');
	$('.page_info').html('<%= escape_javascript(page_entries_info(@invitations, :remote => true).to_s) %>');
<% end %>
$("#flash").html('<%= j render partial: "shared/messages" %>');